name: otaku_scope
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^3.0.0-dev.17
  shimmer: ^3.0.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.0.0
  hooks_riverpod: ^3.0.0-dev.17
  icons_launcher: ^3.0.1
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: 10.0.0
  riverpod_generator: ^3.0.0-dev.17

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
