name: Build and Release Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
          with:
           channel: 'stable'
            cache: true


      - run: flutter pub get
      - run: flutter build apk --release

      - uses: ncipollo/release-action@v1
        with:
          tag: "v1.0.${{ github.run_number }}"
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
